extends: spectral:oas

rules:
  # Phase G1: Ownership Metadata Requirements
  require-x-domain:
    description: All OpenAPI contracts must declare x-domain in info section
    message: "{{property}} must include x-domain extension to identify the business domain"
    given: $.info
    severity: error
    then:
      field: x-domain
      function: truthy
  
  require-x-owner:
    description: All OpenAPI contracts must declare x-owner in info section
    message: "{{property}} must include x-owner extension to identify the domain owner"
    given: $.info
    severity: error
    then:
      field: x-owner
      function: truthy
  
  validate-x-owner-format:
    description: x-owner must be a valid email address
    message: "x-owner must be a valid email address (e.g., owner@skeldir.com)"
    given: $.info.x-owner
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
  
  validate-x-domain-format:
    description: x-domain must follow valid domain naming convention
    message: "x-domain must be a valid domain identifier (e.g., 'auth', 'webhooks/stripe')"
    given: $.info.x-domain
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "^[a-z0-9_/-]+$"
  
  # Operational Requirements
  require-correlation-id-header:
    description: All endpoints should support X-Correlation-ID header for distributed tracing
    message: "{{property}} should include X-Correlation-ID in parameters for traceability"
    given: $.paths[*][get,post,put,patch,delete]
    severity: warn
    then:
      field: parameters
      function: schema
      functionOptions:
        schema:
          type: array
          contains:
            properties:
              name:
                const: X-Correlation-ID
              in:
                const: header
  
  require-operation-id:
    description: All operations must have an operationId
    message: "{{property}} must have an operationId for code generation and coverage tracking"
    given: $.paths[*][get,post,put,patch,delete]
    severity: error
    then:
      field: operationId
      function: truthy
  
  # Error Response Standards
  use-problem-schema-for-errors:
    description: Error responses should reference the Problem schema (RFC 7807)
    message: "{{property}} error responses should use $ref to Problem schema"
    given: $.paths[*][*].responses[?(@property >= '400' && @property < '600')]
    severity: warn
    then:
      field: content.application/json.schema.$ref
      function: pattern
      functionOptions:
        match: ".*Problem.*"
  
  # API Design Standards
  operation-description:
    description: All operations should have a description
    message: "{{property}} should have a description explaining its purpose"
    given: $.paths[*][get,post,put,patch,delete]
    severity: warn
    then:
      field: description
      function: truthy
  
  operation-tags:
    description: All operations should have tags for organization
    message: "{{property}} should have at least one tag"
    given: $.paths[*][get,post,put,patch,delete]
    severity: warn
    then:
      field: tags
      function: truthy
  
  # Security Requirements
  operation-security-defined:
    description: All operations should explicitly define security requirements
    message: "{{property}} must explicitly define security (use empty array [] for public endpoints)"
    given: $.paths[*][get,post,put,patch,delete]
    severity: error
    then:
      field: security
      function: defined
  
  # Schema Standards
  component-schema-description:
    description: Component schemas should have descriptions
    message: "{{property}} should have a description"
    given: $.components.schemas[*]
    severity: warn
    then:
      field: description
      function: truthy
  
  # Phase G3: Invariant Enforcement Rules
  no-unconstrained-currency:
    description: Currency fields must use ISO 4217 pattern (uppercase or lowercase for Stripe)
    message: "{{property}} must have a pattern constraint (ISO 4217: ^[A-Z]{3}$ or ^[a-z]{3}$ for Stripe)"
    given: $..properties[?(@property === 'currency')]
    severity: error
    then:
      field: pattern
      function: truthy
  
  no-negative-monetary-values:
    description: Revenue and amount fields must have minimum constraint of 0
    message: "{{property}} must have minimum: 0 constraint (monetary values cannot be negative)"
    given: $..properties[?(@property =~ /^(total_revenue|revenue|amount|total|price)$/)]
    severity: error
    then:
      field: minimum
      function: defined
  
  no-loose-strings:
    description: String fields should have format, pattern, enum, or maxLength constraints
    message: "{{property}} of type string should have format, pattern, enum, or maxLength to prevent unconstrained data"
    given: $..properties[?(@.type === 'string' && @property !== 'description' && @property !== 'detail' && @property !== 'message')]
    severity: warn
    then:
      function: schema
      functionOptions:
        schema:
          anyOf:
            - required: [format]
            - required: [pattern]
            - required: [enum]
            - required: [maxLength]
  
  rate-limit-headers-in-429:
    description: 429 responses must include all rate limit headers
    message: "429 responses must include X-RateLimit-Limit, X-RateLimit-Remaining, and X-RateLimit-Reset headers"
    given: $..responses['429'].headers
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          required:
            - X-RateLimit-Limit
            - X-RateLimit-Remaining
            - X-RateLimit-Reset
  
  uuid-format-for-ids:
    description: ID fields with UUID semantics must use format uuid
    message: "{{property}} should use format: uuid for consistent identifier format"
    given: $..properties[?(@property =~ /^(tenant_id|correlation_id|error_id)$/)]
    severity: error
    then:
      field: format
      function: pattern
      functionOptions:
        match: "uuid"
  
  timestamp-format-required:
    description: Timestamp fields must use format date-time (RFC 3339)
    message: "{{property}} must use format: date-time for RFC 3339 compliance"
    given: $..properties[?(@property =~ /^(timestamp|created_at|updated_at|last_run_at|event_timestamp|create_time|date_created)$/)]
    severity: error
    then:
      field: format
      function: pattern
      functionOptions:
        match: "date-time"
  
  state-fields-use-enum:
    description: State and status fields should use enum constraints
    message: "{{property}} should use enum constraint to define valid state values explicitly"
    given: $..properties[?(@property =~ /^(state|status|token_type)$/)]
    severity: warn
    then:
      field: enum
      function: truthy
  
  non-negative-integers:
    description: Count, limit, and ID fields should have minimum constraints
    message: "{{property}} should have minimum: 0 or minimum: 1 constraint"
    given: $..properties[?(@.type === 'integer' && @property =~ /^(limit|count|expires_in|data_freshness_seconds|amount)$/)]
    severity: error
    then:
      field: minimum
      function: defined

