"""
Dynamic Contract Conformance Tests - Phase CF4

This module uses Schemathesis to validate runtime behavior against OpenAPI contracts.
Tests ensure that:
- Response status codes match contract-defined allowed statuses
- Response payloads validate against OpenAPI schemas
- Error responses conform to RFC7807 Problem schema

This is the behavioral validation layer: structure can match but behavior can drift.
Dynamic conformance catches status code changes, missing fields, and schema violations.

Coverage Requirement: All in-scope operations hit at least once.
"""

import pytest
import schemathesis
from pathlib import Path
from typing import List
import yaml

# Import FastAPI app for ASGI testing (no network required)
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "backend"))
from app.main import app


def load_scope_config() -> dict:
    """Load contract scope configuration."""
    config_path = Path(__file__).parent.parent.parent / "backend" / "app" / "config" / "contract_scope.yaml"
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)


def get_bundled_specs() -> List[Path]:
    """Get all bundled OpenAPI specifications."""
    bundles_dir = Path(__file__).parent.parent.parent / "api-contracts" / "dist" / "openapi" / "v1"
    return list(bundles_dir.glob("*.bundled.yaml"))


# Load scope configuration
config = load_scope_config()
in_scope_prefixes = config.get('in_scope_prefixes', [])


def is_in_scope(path: str) -> bool:
    """Check if path is in scope for contract enforcement."""
    for prefix in in_scope_prefixes:
        if path.startswith(prefix):
            return True
    return False


# Test each bundled specification
bundled_specs = get_bundled_specs()


@pytest.mark.parametrize("spec_path", bundled_specs, ids=lambda p: p.name)
def test_contract_semantic_conformance(spec_path: Path):
    """
    Test that FastAPI implementation conforms to OpenAPI contract at runtime.
    
    This test:
    1. Loads the bundled OpenAPI specification
    2. Generates test cases for all operations
    3. Executes requests against FastAPI app (ASGI, no network)
    4. Validates response status codes match contract
    5. Validates response bodies match OpenAPI schemas
    
    Any mismatch indicates contract-implementation divergence.
    """
    # Load schema with Schemathesis
    schema = schemathesis.from_path(str(spec_path), app=app)
    
    # Track coverage
    operations_tested = []
    operations_failed = []
    
    # Test all operations in the schema
    @schema.parametrize()
    def run_test(case):
        """Execute test case generated by Schemathesis."""
        # Skip if not in scope
        if not is_in_scope(case.path):
            pytest.skip(f"Path {case.path} is out of scope")
        
        operations_tested.append(f"{case.method} {case.path}")
        
        # Execute request via ASGI (no network)
        try:
            response = case.call_asgi()
            
            # Validate response
            case.validate_response(response)
            
        except Exception as e:
            operations_failed.append({
                'operation': f"{case.method} {case.path}",
                'error': str(e)
            })
            raise
    
    # Run the parametrized test
    try:
        run_test()
    except Exception:
        # If any operations failed, report them
        if operations_failed:
            failure_report = "\n".join([
                f"  - {op['operation']}: {op['error']}"
                for op in operations_failed
            ])
            pytest.fail(
                f"Contract semantic validation failed for {len(operations_failed)} operation(s):\n"
                f"{failure_report}"
            )
    
    # Assert at least one operation was tested
    assert len(operations_tested) > 0, f"No operations tested from {spec_path.name}"


def test_auth_login_happy_path():
    """
    Test auth login endpoint with valid request.
    
    This explicit test supplements Schemathesis coverage with business logic validation.
    """
    from fastapi.testclient import TestClient
    import uuid
    
    client = TestClient(app)
    
    response = client.post(
        "/api/auth/login",
        json={
            "email": "user@example.com",
            "password": "securePassword123"
        },
        headers={"X-Correlation-ID": str(uuid.uuid4())}
    )
    
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    
    data = response.json()
    assert "access_token" in data, "Missing access_token in response"
    assert "refresh_token" in data, "Missing refresh_token in response"
    assert "expires_in" in data, "Missing expires_in in response"
    assert "token_type" in data, "Missing token_type in response"
    assert data["token_type"] == "Bearer", "Expected token_type to be 'Bearer'"


def test_attribution_revenue_realtime_happy_path():
    """
    Test attribution revenue endpoint with valid request.
    
    This explicit test supplements Schemathesis coverage.
    """
    from fastapi.testclient import TestClient
    import uuid
    
    client = TestClient(app)
    
    response = client.get(
        "/api/attribution/revenue/realtime",
        headers={"X-Correlation-ID": str(uuid.uuid4())}
    )
    
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    
    data = response.json()
    assert "total_revenue" in data, "Missing total_revenue in response"
    assert "verified" in data, "Missing verified in response"
    assert "data_freshness_seconds" in data, "Missing data_freshness_seconds in response"
    assert "tenant_id" in data, "Missing tenant_id in response"
    
    # Validate types
    assert isinstance(data["total_revenue"], str), "total_revenue should be string"
    assert isinstance(data["verified"], bool), "verified should be boolean"
    assert isinstance(data["data_freshness_seconds"], int), "data_freshness_seconds should be int"


def test_coverage_report():
    """
    Generate coverage report showing which operations were tested.
    
    This helps verify the "all operations hit at least once" requirement.
    """
    from fastapi.testclient import TestClient
    
    client = TestClient(app)
    
    # Get all routes from app
    in_scope_routes = []
    for route in app.routes:
        if hasattr(route, 'path') and hasattr(route, 'methods'):
            path = route.path
            if is_in_scope(path):
                for method in route.methods:
                    if method not in ('HEAD', 'OPTIONS'):
                        in_scope_routes.append(f"{method} {path}")
    
    print(f"\nContract Coverage Report:")
    print(f"  Total in-scope routes: {len(in_scope_routes)}")
    print(f"  Routes:")
    for route in sorted(in_scope_routes):
        print(f"    - {route}")


# Negative test scenarios (documented in negative_tests_dynamic.md)
# These should be run manually on test branches to validate enforcement


if __name__ == "__main__":
    # Allow running directly for quick testing
    pytest.main([__file__, "-v"])



