# generated by datamodel-codegen:
#   filename:  attribution.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, Field


class RealtimeRevenueCounter(BaseModel):
    total_revenue: Annotated[float, Field(example=125430.5)]
    """
    Total verified revenue amount in USD
    """
    event_count: Annotated[int, Field(example=1247, ge=0)]
    """
    Number of revenue events tracked
    """
    last_updated: Annotated[datetime, Field(example='2025-11-26T14:32:00Z')]
    """
    ISO 8601 timestamp of last data update
    """
    data_freshness_seconds: Annotated[int, Field(example=5, ge=0)]
    """
    Seconds since data was last refreshed
    """
    verified: Annotated[bool, Field(example=True)]
    """
    Whether revenue is verified through payment reconciliation
    """
    tenant_id: Annotated[str, Field(example='00000000-0000-0000-0000-000000000000')]
    """
    Tenant identifier associated with the revenue data
    """
    confidence_score: Annotated[
        Optional[float], Field(example=0.94, ge=0.0, le=1.0)
    ] = None
    """
    Statistical confidence score (0-1) for attribution accuracy
    """
    upgrade_notice: Annotated[
        Optional[str], Field(example='Upgrade to Pro for historical analytics')
    ] = None
    """
    Optional message about upgrading for more features
    """


class ChannelName(Enum):
    """
    Marketing channel name
    """

    Meta = 'Meta'
    Google = 'Google'
    TikTok = 'TikTok'
    LinkedIn = 'LinkedIn'
    Organic = 'Organic'
    Direct = 'Direct'
    Email = 'Email'
    Referral = 'Referral'


class ChannelAttribution(BaseModel):
    channel_name: ChannelName
    """
    Marketing channel name
    """
    revenue: float
    """
    Attributed revenue for this channel
    """
    conversion_count: int
    """
    Number of conversions attributed to this channel
    """
    confidence_score: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Statistical confidence in attribution accuracy
    """
    spend: Optional[float] = None
    """
    Marketing spend on this channel
    """
    roas: Optional[float] = None
    """
    Return on Ad Spend (revenue/spend)
    """


# Alias for CI compatibility (must be a class definition to match workflow grep pattern)
class RealtimeRevenueResponse(RealtimeRevenueCounter):
    """Alias for RealtimeRevenueCounter to match CI expectations."""
    pass
