# generated by datamodel-codegen:
#   filename:  export.bundled.yaml

from __future__ import annotations

from typing import Annotated, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class ExportRevenueResponse(BaseModel):
    file_url: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/exports/revenue_20251110.json')
    ]
    """
    URL to download the exported file
    """
    tenant_id: Annotated[UUID, Field(example='550e8400-e29b-41d4-a716-446655440000')]
    """
    Tenant identifier
    """


class ExportAllocationsResponse(BaseModel):
    file_url: Annotated[
        AnyUrl,
        Field(example='https://api.skeldir.com/exports/allocations_20251110.json'),
    ]
    """
    URL to download the exported allocations file
    """
    tenant_id: Annotated[UUID, Field(example='550e8400-e29b-41d4-a716-446655440000')]
    """
    Tenant identifier
    """


class ExportEventsResponse(BaseModel):
    file_url: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/exports/events_20251110.json')
    ]
    """
    URL to download the exported events file
    """
    tenant_id: Annotated[UUID, Field(example='550e8400-e29b-41d4-a716-446655440000')]
    """
    Tenant identifier
    """


class Problem(BaseModel):
    type: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/problems/validation-error')
    ]
    """
    URI reference that identifies the problem type
    """
    title: Annotated[str, Field(example='Validation Error')]
    """
    Short, human-readable summary of the problem type
    """
    status: Annotated[int, Field(example=400)]
    """
    HTTP status code
    """
    detail: Annotated[str, Field(example='The request body failed validation')]
    """
    Human-readable explanation specific to this occurrence
    """
    instance: Annotated[
        Optional[AnyUrl], Field(example='/api/attribution/revenue/realtime')
    ] = None
    """
    URI reference that identifies the specific occurrence of the problem
    """
    error_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Unique identifier for this error occurrence (Skeldir extension)
    """
    correlation_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Correlation ID from the request header (Skeldir extension)
    """
