# generated by datamodel-codegen:
#   filename:  reconciliation.bundled.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class State(Enum):
    """
    Current state of the reconciliation pipeline
    """

    idle = 'idle'
    running = 'running'
    failed = 'failed'
    completed = 'completed'


class ReconciliationStatusResponse(BaseModel):
    state: Annotated[State, Field(example='completed')]
    """
    Current state of the reconciliation pipeline
    """
    last_run_at: Annotated[datetime, Field(example='2025-11-10T14:30:00Z')]
    """
    Timestamp of the last reconciliation run
    """
    tenant_id: Annotated[UUID, Field(example='550e8400-e29b-41d4-a716-446655440000')]
    """
    Tenant identifier
    """


class Status(Enum):
    """
    Reconciliation status for the transaction
    """

    reconciled = 'reconciled'
    pending = 'pending'
    failed = 'failed'


class TransactionRecord(BaseModel):
    transaction_id: str
    """
    Unique transaction identifier
    """
    amount: float
    """
    Transaction amount
    """
    currency: str
    """
    ISO currency code
    """
    status: Status
    """
    Reconciliation status for the transaction
    """
    occurred_at: datetime
    """
    Timestamp when the transaction occurred
    """
    tenant_id: UUID
    """
    Tenant identifier
    """


class DiscrepancyRecord(BaseModel):
    discrepancy_id: str
    """
    Unique discrepancy identifier
    """
    transaction_id: str
    """
    Related transaction identifier
    """
    expected_amount: float
    """
    Expected transaction amount
    """
    observed_amount: float
    """
    Observed transaction amount
    """
    currency: str
    """
    ISO currency code
    """
    reason: str
    """
    Reason for discrepancy
    """
    detected_at: datetime
    """
    Timestamp when discrepancy was detected
    """
    tenant_id: UUID
    """
    Tenant identifier
    """


class Problem(BaseModel):
    type: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/problems/validation-error')
    ]
    """
    URI reference that identifies the problem type
    """
    title: Annotated[str, Field(example='Validation Error')]
    """
    Short, human-readable summary of the problem type
    """
    status: Annotated[int, Field(example=400)]
    """
    HTTP status code
    """
    detail: Annotated[str, Field(example='The request body failed validation')]
    """
    Human-readable explanation specific to this occurrence
    """
    instance: Annotated[
        Optional[AnyUrl], Field(example='/api/attribution/revenue/realtime')
    ] = None
    """
    URI reference that identifies the specific occurrence of the problem
    """
    error_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Unique identifier for this error occurrence (Skeldir extension)
    """
    correlation_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Correlation ID from the request header (Skeldir extension)
    """
