# generated by datamodel-codegen:
#   filename:  revenue.bundled.yaml

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class RealtimeRevenueV1Response(BaseModel):
    tenant_id: Annotated[UUID, Field(example="00000000-0000-0000-0000-000000000000")]
    """
    Tenant identifier associated with the revenue data
    """
    interval: Annotated[str, Field(example="minute")]
    """
    Time interval represented by the aggregate
    """
    currency: Annotated[str, Field(example="USD", min_length=3, max_length=3)]
    """
    ISO 4217 currency code
    """
    revenue_total: Annotated[float, Field(example=125430.5, ge=0)]
    """
    Total revenue amount for the interval
    """
    verified: Annotated[bool, Field(example=False)]
    """
    Whether revenue is verified through payment reconciliation
    """
    data_as_of: Annotated[Optional[datetime], Field(example="2026-01-26T12:00:00Z")] = None
    """
    Timestamp of the last successful upstream data fetch (nullable during interim)
    """
    sources: Annotated[Optional[list[str]], Field(example=["meta", "google"])] = None
    """
    Optional list of platform source identifiers
    """
