# generated by datamodel-codegen:
#   filename:  trust-simulations.yaml

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class SimulationSubmission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_envelope_id: constr(pattern=r'^env_[a-f0-9]{32}$')
    source_final_envelope_hash: constr(pattern=r'^sha256:[a-f0-9]{64}$')
    total_budget_minor: conint(ge=1, le=9007199254740991, strict=True)
    request_ref: constr(pattern=r'^[A-Za-z0-9._:-]+$', min_length=1, max_length=128)
