# generated by datamodel-codegen:
#   filename:  webhooks.paypal.bundled.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class Amount(BaseModel):
    """
    Transaction amount object
    """

    total: Optional[str] = None
    """
    Total amount as string (will be converted to cents)
    """
    currency: Annotated[Optional[str], Field(example='USD', pattern='^[A-Z]{3}$')] = None
    """
    ISO 4217 uppercase currency code
    """


class PayPalSaleCompletedRequest(BaseModel):
    """
    PayPal sale webhook payload. Note: PII fields (payer email, payer information, shipping address)
    are stripped before persistence. Only transaction ID, amount, currency, and create_time are retained.

    """

    id: Optional[str] = None
    """
    PayPal transaction ID (used for idempotency)
    """
    amount: Optional[Amount] = None
    """
    Transaction amount object
    """
    create_time: Optional[datetime] = None
    """
    Transaction creation timestamp
    """


class Amount1(BaseModel):
    """
    Refund amount object
    """

    total: Annotated[Optional[str], Field(example='39.99')] = None
    """
    Total refund amount as string (will be converted to cents)
    """
    currency: Annotated[Optional[str], Field(example='USD', pattern='^[A-Z]{3}$')] = None
    """
    ISO 4217 uppercase currency code
    """


class State(Enum):
    """
    Refund state
    """

    completed = 'completed'
    pending = 'pending'


class PayPalSaleRefundedRequest(BaseModel):
    """
    PayPal sale refunded webhook payload. Note: PII fields (payer email, payer information, shipping address)
    are stripped before persistence. Only refund ID, transaction ID, refund amount, and timestamp are retained.

    """

    id: Annotated[Optional[str], Field(example='RF123456789')] = None
    """
    PayPal refund ID (used for idempotency)
    """
    parent_payment: Annotated[Optional[str], Field(example='PAY-123456789')] = None
    """
    PayPal transaction ID being refunded
    """
    amount: Optional[Amount1] = None
    """
    Refund amount object
    """
    create_time: Annotated[
        Optional[datetime], Field(example='2025-11-10T15:30:00Z')
    ] = None
    """
    Refund creation timestamp
    """
    state: Annotated[Optional[State], Field(example='completed')] = None
    """
    Refund state
    """


class WebhookAcknowledgement(BaseModel):
    acknowledged: Annotated[bool, Field(example=True)]
    event_id: Annotated[str, Field(example='evt_550e8400e29b41d4a716446655440000')]
    """
    Internal event ID for tracking
    """


class Problem(BaseModel):
    type: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/problems/validation-error')
    ]
    """
    URI reference that identifies the problem type
    """
    title: Annotated[str, Field(example='Validation Error')]
    """
    Short, human-readable summary of the problem type
    """
    status: Annotated[int, Field(example=400)]
    """
    HTTP status code
    """
    detail: Annotated[str, Field(example='The request body failed validation')]
    """
    Human-readable explanation specific to this occurrence
    """
    instance: Annotated[
        Optional[AnyUrl], Field(example='/api/attribution/revenue/realtime')
    ] = None
    """
    URI reference that identifies the specific occurrence of the problem
    """
    error_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Unique identifier for this error occurrence (Skeldir extension)
    """
    correlation_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Correlation ID from the request header (Skeldir extension)
    """
