# generated by datamodel-codegen:
#   filename:  webhooks.shopify.bundled.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class ShopifyOrderCreateRequest(BaseModel):
    """
    Shopify order webhook payload. Note: PII fields (email, billing_address, shipping_address, customer details)
    are stripped before persistence. Only transaction ID, order total, currency, and timestamp are retained.

    """

    id: Optional[int] = None
    """
    Shopify order ID (used for idempotency)
    """
    total_price: Optional[str] = None
    """
    Order total as string (will be converted to cents)
    """
    currency: Annotated[Optional[str], Field(example='USD', pattern='^[A-Z]{3}$')] = None
    """
    ISO 4217 uppercase currency code
    """
    created_at: Optional[datetime] = None
    """
    Order creation timestamp
    """


class FinancialStatus(Enum):
    """
    Financial status of the order
    """

    paid = 'paid'
    partially_paid = 'partially_paid'


class ShopifyOrderPaidRequest(BaseModel):
    """
    Shopify order paid webhook payload. Note: PII fields (email, billing_address, shipping_address, customer details)
    are stripped before persistence. Only transaction ID, order total, currency, and timestamp are retained.

    """

    id: Annotated[Optional[int], Field(example=1234567890, ge=1)] = None
    """
    Shopify order ID (used for idempotency)
    """
    total_price: Annotated[Optional[str], Field(example='129.99')] = None
    """
    Order total as string (will be converted to cents)
    """
    currency: Annotated[Optional[str], Field(example='USD', pattern='^[A-Z]{3}$')] = None
    """
    ISO 4217 uppercase currency code
    """
    financial_status: Annotated[Optional[FinancialStatus], Field(example='paid')] = None
    """
    Financial status of the order
    """
    created_at: Annotated[Optional[datetime], Field(example='2025-11-10T14:30:00Z')] = (
        None
    )
    """
    Order creation timestamp
    """


class ShopifyRefundCreateRequest(BaseModel):
    """
    Shopify refund creation webhook payload. Note: PII fields (email, billing_address, shipping_address, customer details)
    are stripped before persistence. Only refund ID, order ID, refund amount, and timestamp are retained.

    """

    id: Annotated[Optional[int], Field(example=9876543210, ge=1)] = None
    """
    Shopify refund ID (used for idempotency)
    """
    order_id: Annotated[Optional[int], Field(example=1234567890, ge=1)] = None
    """
    Shopify order ID being refunded
    """
    refund_amount: Annotated[Optional[str], Field(example='29.99')] = None
    """
    Refund amount as string (will be converted to cents)
    """
    currency: Annotated[Optional[str], Field(example='USD', pattern='^[A-Z]{3}$')] = None
    """
    ISO 4217 uppercase currency code
    """
    created_at: Annotated[Optional[datetime], Field(example='2025-11-10T15:30:00Z')] = (
        None
    )
    """
    Refund creation timestamp
    """


class WebhookAcknowledgement(BaseModel):
    acknowledged: Annotated[bool, Field(example=True)]
    event_id: Annotated[str, Field(example='evt_550e8400e29b41d4a716446655440000')]
    """
    Internal event ID for tracking
    """


class Problem(BaseModel):
    type: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/problems/validation-error')
    ]
    """
    URI reference that identifies the problem type
    """
    title: Annotated[str, Field(example='Validation Error')]
    """
    Short, human-readable summary of the problem type
    """
    status: Annotated[int, Field(example=400)]
    """
    HTTP status code
    """
    detail: Annotated[str, Field(example='The request body failed validation')]
    """
    Human-readable explanation specific to this occurrence
    """
    instance: Annotated[
        Optional[AnyUrl], Field(example='/api/attribution/revenue/realtime')
    ] = None
    """
    URI reference that identifies the specific occurrence of the problem
    """
    error_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Unique identifier for this error occurrence (Skeldir extension)
    """
    correlation_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Correlation ID from the request header (Skeldir extension)
    """
