# generated by datamodel-codegen:
#   filename:  webhooks.stripe.bundled.yaml

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class StripeChargeSucceededRequest(BaseModel):
    """
    Stripe charge webhook payload. Note: PII fields (customer email, billing details, payment method details)
    are stripped before persistence. Only charge ID, amount, currency, and created timestamp are retained.

    """

    id: Optional[str] = None
    """
    Stripe charge ID (used for idempotency)
    """
    amount: Optional[int] = None
    """
    Charge amount in cents
    """
    currency: Annotated[Optional[str], Field(example='usd', pattern='^[a-z]{3}$')] = None
    """
    ISO 4217 currency code (lowercase per Stripe API specification)
    """
    created: Optional[int] = None
    """
    Unix timestamp of charge creation
    """


class StripeChargeRefundedRequest(BaseModel):
    """
    Stripe charge refunded webhook payload. Note: PII fields (customer email, billing details, payment method details)
    are stripped before persistence. Only charge ID, refund amount, currency, and created timestamp are retained.

    """

    id: Annotated[
        Optional[str], Field(example='ch_1234567890abcdefg', pattern='^ch_[a-zA-Z0-9]+$')
    ] = None
    """
    Stripe charge ID (used for idempotency)
    """
    amount_refunded: Annotated[Optional[int], Field(example=5000, ge=0)] = None
    """
    Refund amount in cents
    """
    currency: Annotated[Optional[str], Field(example='usd', pattern='^[a-z]{3}$')] = None
    """
    ISO 4217 currency code (lowercase per Stripe API specification)
    """
    created: Annotated[Optional[int], Field(example=1609459200)] = None
    """
    Unix timestamp of refund creation
    """
    refunded: Annotated[Optional[bool], Field(example=True)] = None
    """
    Whether the charge has been refunded (always true for this event)
    """


class Status(Enum):
    """
    Payment intent status (succeeded for this event)
    """

    succeeded = 'succeeded'


class StripePaymentIntentSucceededRequest(BaseModel):
    """
    Stripe payment_intent.succeeded webhook payload for modern Payment Intents API.
    Note: PII fields (customer email, billing details, payment method details) are stripped before persistence.
    Only payment intent ID, amount, currency, and created timestamp are retained.

    """

    id: Annotated[
        Optional[str], Field(example='pi_1234567890abcdefg', pattern='^pi_[a-zA-Z0-9]+$')
    ] = None
    """
    Stripe payment intent ID (used for idempotency)
    """
    amount: Annotated[Optional[int], Field(example=10000, ge=0)] = None
    """
    Payment amount in cents
    """
    currency: Annotated[Optional[str], Field(example='usd', pattern='^[a-z]{3}$')] = None
    """
    ISO 4217 currency code (lowercase per Stripe API specification)
    """
    created: Annotated[Optional[int], Field(example=1609459200)] = None
    """
    Unix timestamp of payment intent creation
    """
    status: Annotated[Optional[Status], Field(example='succeeded')] = None
    """
    Payment intent status (succeeded for this event)
    """


class WebhookAcknowledgement(BaseModel):
    acknowledged: Annotated[bool, Field(example=True)]
    event_id: Annotated[str, Field(example='evt_550e8400e29b41d4a716446655440000')]
    """
    Internal event ID for tracking
    """


class Problem(BaseModel):
    type: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/problems/validation-error')
    ]
    """
    URI reference that identifies the problem type
    """
    title: Annotated[str, Field(example='Validation Error')]
    """
    Short, human-readable summary of the problem type
    """
    status: Annotated[int, Field(example=400)]
    """
    HTTP status code
    """
    detail: Annotated[str, Field(example='The request body failed validation')]
    """
    Human-readable explanation specific to this occurrence
    """
    instance: Annotated[
        Optional[AnyUrl], Field(example='/api/attribution/revenue/realtime')
    ] = None
    """
    URI reference that identifies the specific occurrence of the problem
    """
    error_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Unique identifier for this error occurrence (Skeldir extension)
    """
    correlation_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Correlation ID from the request header (Skeldir extension)
    """
